# ??? ?????? ???????
spring.application.name=kinopoisk-service

# ????????? ??????????? ? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/kinopoisk_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ????????? JPA / Hibernate
# validate ?????????, ??? ????????? ??????? ? Java ????????????? ???????? ? ???? ??????
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ????????? Flyway
# ???????? ?????????????? ?????? ???????? ??? ?????? ?????????
spring.flyway.enabled=true

# ????? ??? ??????? ? API ??????????
kinopoisk.api.token=a6e17ae6-2e47-47af-9ebb-ebb8d3184f64

# ????????? ???????? Email ????? SMTP (?????? ??? ??????)
spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.username=????_?????@yandex.ru
spring.mail.password=????_??????_??????????
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true