# ??? ?????? ???????
spring.application.name=kinopoisk-service

# ????????? ??????????? ? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/kinopoisk_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ????????? JPA / Hibernate
# validate ?????????, ??? ????????? ??????? ? Java ????????????? ???????? ? ???? ??????
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ????????? Flyway
# ???????? ?????????????? ?????? ???????? ??? ?????? ?????????
spring.flyway.enabled=true